name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: ['12.x', '13.x']
        include:
          - node-version: '13.x'
            report-coverage: true
    name: Node ${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: yarn install
      - name: Bootstrap Lerna
        run: yarn run bootstrap
      - name: Test w/ Reporting
        if: matrix.report-coverage
        uses: paambaati/codeclimate-action@v2.3.0
        env:
          CC_TEST_REPORTER_ID: 0b711def417a17c0ea9a1d7654d17ededa1d7f83d03ac297bf900711636a581c
        with:
          coverageCommand: yarn test --coverage
      - name: Test w/o Reporting
        if: '!matrix.report-coverage'
        run: yarn test
