name: Test PRs
on:
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        node-version: ['12.x', '13.x']
    name: Test with Node ${{ matrix.node-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: yarn install
      - name: Bootstrap Lerna
        run: yarn run bootstrap
      - name: Test w/o Reporting
        run: yarn test
